# Generated by Django 3.1.3 on 2020-12-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='sponsor_deadline',
            field=models.DateField(),
        ),
    ]
