# Generated by Django 3.1.3 on 2020-12-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_remove_update_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
