# Generated by Django 3.1.3 on 2020-12-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_auto_20201202_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='estimated_harvest',
            field=models.DateTimeField(),
        ),
    ]
