# Generated by Django 3.1.3 on 2020-12-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_auto_20201206_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='featured_image',
        ),
    ]
