# Generated by Django 3.1.3 on 2020-12-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0004_remove_garden_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='amount_raised',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
