# Generated by Django 3.1.3 on 2020-12-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0005_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
