# Generated by Django 3.1.3 on 2020-12-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0005_auto_20201206_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='field_name',
            field=models.ImageField(default=' ', upload_to='media'),
            preserve_default=False,
        ),
    ]
